# Generated by Django 3.0.5 on 2020-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yayinEvi',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='yazar',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
