# Generated by Django 3.0.5 on 2020-06-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200605_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='yayinEvi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yazar',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
